### ISSUE TITLE
Open gmic-qt with file

### ISSUE THREAD

**Issue by sati32** [c-koi/gmic-qt#61] opened 2019-02-03 06:51 UTC
I am one of the developers of PhotoLine image processing software (www.pl32.com).
Users told me, that it is no longer possible to use gmic-qt as an external program in PhotoLine.
PhotoLine has an external program interface. This way, PhotoLine starts an external program and passes a TIFF or PNG image to this program. When the image is changed, PhotoLine updates automaticalla.
One of you last releases removed the option to pass an image to gmic-qt when starting it.
Can you fix this?

**Comment by c-koi** [comment] 2019-02-04 15:37
The option has not been removed, nor modified.
Note that the input image must be the first arg on command line, though.
Maybe some changes have been introduced by the "users" in the way PhotoLine calls the gmic_qt program?

**Comment by sati32** [comment] 2019-02-04 15:55
Sorry, I am new on gmic-qt, but I think the "normal" Windows version is no longer available.
Our users did use this. Now they use the Krita or Paint.net version.
I can start this versions here on Windows, but when I call it with an image file, the image is not opened,

**Comment by sati32** [comment] 2019-02-06 07:14
I noticed that the paint.net version works with files. The problem at the moment is, that you have to pass two source files and one destination file. But when I send the same file name 3 times, it will work. So I will add such an option in PhotoLine and our users can work with the paint.net version.

**Comment by 0xC0000054** [comment] 2019-02-06 22:28
> The problem at the moment is, that you have to pass two source files and one destination file.

You can pass the same filename twice.

The use of 3 files is a hack to allow Paint.NET to use G'MIC filters that require multiple layers.
The second image is a different layer in the Paint.NET document that the user can place on the clipboard.

Once Paint.NET allows its plugins to access all of the document layers, I will be changing the Paint.NET G'MIC-Qt plugin to use another method.

The most robust solution would be for PhotoLine to have its own G'MIC-Qt host plugin.

**Comment by sati32** [comment] 2019-02-07 08:22
Yes, I see. I will pass a second layer, when there is one, like Paint.NET does.
Changing the interface is not so good :-(
To build a new API for PhotoLine is not what you should do. I on your place would build one API and one plugin and the host should support this.
This way I had a look on the Krita interface, but I didn't find a documentation and didn't understand how it works.

**Comment by 0xC0000054** [comment] 2019-02-07 10:53
>  This way I had a look on the Krita interface, but I didn't find a documentation and didn't understand how it works.

Krita appears to be communicating with its G'MIC plugin using named pipes and shared memory.
The G'MIC application plugins are not intended to be used by multiple hosts, each plugin is tightly coupled with the image application it is designed to support.

>  Changing the interface is not so good :-(

As stated above, each host application uses its own interface to G'MIC-Qt, and that interface is not intended for use my other applications.

The fact that the Paint.NET plugin currently uses files on the command line is an implementation detail that will likely change in a future version.
I am currently investigating how to change the Paint.NET G'MIC plugin to use named pipes for inter-process communication.

> To build a new API for PhotoLine is not what you should do

That is the best way to make G'MIC-Qt work with PhotoLine's external program command.

From the [G'MIC QT no longer working with PhotoLine](https://www.pl32.com/forum3/viewtopic.php?f=1&p=45465&sid=03fc14f7062e7e5366a9e1d393035203#p45465) thread it appears the issue is that the G'MIC developers are no longer distributing pre-compiled versions of the G'MIC-Qt standalone version.

Here are the Windows build instructions:

1. Download and install the 64-bit version of [MSYS 2](https://www.msys2.org/).
2. Install the G'MIC-Qt dependencies using the following command in the MSYS shell:
`pacman -S git mingw-w64-x86_64-toolchain mingw-w64-x86_64-curl mingw-w64-x86_64-fftw mingw-w64-x86_64-qt5`
3. Once all those files are installed you should be ready to build G'MIC-Qt
4. Make a new directory and change into it.
'mkdir gmic-build && cd gmic-build'
5. Setup G'MIC-Qt and build the standalone version:

git clone https://github.com/dtschump/gmic.git
git clone https://github.com/c-koi/gmic-qt.git
make -C gmic/src CImg.h gmic_stdlib.h
cd gmic-qt
qmake HOST=none PRERELEASE=""
make release

You should be able to copy the dependent DLL files from the 64-bit Paint.NET download.

**Comment by sati32** [comment] 2019-10-12 07:15
Hi,
      
    
    
      
      The fact that the Paint.NET plugin currently uses files on the
      command line is an implementation detail that will likely change
      in a future version.
      
        I am currently investigating how to change the Paint.NET G'MIC
        plugin to use named pipes for inter-process communication.
      
        To build a new API for PhotoLine is not what you should do
      
    
    
    I think you did it. G'MIC will no longer work with PhotoLine. I got
    a message in our forum.
    Is there a documentation for the new interface?
    Sorry, but I think nobody here will build a G'MIC Qt for PhotoLine,
    so I see no other way to support it.
    
    
    Gerhard Huber
    support@pl32.de - www.pl32.de
    
    --
    Computerinsel GmbH,
    Zur Limestherme 4, 93333 Bad Gögging
    Amtsgericht Regensburg, HRB 5891
    Geschäftsführer: Gerhard Huber, Martin Huber 
    USt. ID: DE 169241796

**Comment by 0xC0000054** [comment] 2019-10-12 19:26
> Is there a documentation for the new interface?

No there is not.
As I previously stated the plugin interface an implementation detail that is subject to change, the Paint.NET G'MIC binaries are only guaranteed to be compatible with the same version of the Paint.NET plugin.

> Sorry, but I think nobody here will build a G'MIC Qt for PhotoLine,
    so I see no other way to support it.

You could have your users configure Paint.NET as an external program in PhotoLine.

**Comment by sati32** [comment] 2019-10-17 08:00
Hi,
    
    
      
        Is there a documentation for the new interface?
      
      No there is not.
        As I previously stated the plugin interface an implementation
        detail that is subject to change, the Paint.NET G'MIC binaries
        are only guaranteed to be compatible with the same version of
        the Paint.NET plugin.
      
        Sorry, but I think nobody here will build a G'MIC Qt for
          PhotoLine,
          so I see no other way to support it.
      
      You could have your users configure Paint.NET as an external
        program in PhotoLine.
    
    
    that's not the intended way I think.
    So I had a look on the source code of gmic-qt to build it with a
    interface for PhotoLine.
    First I installed QT-Creator and tried to compile the Gimp plugin. I
    am sorry, but I didn't manage to compile it.
    I think it is possible to compile it under Windows 10?
    I get the error message, that CImg.h is missing. Do you have any
    help for me?

**Comment by 0xC0000054** [comment] 2019-10-17 21:15
> I think it is possible to compile it under Windows 10?

Yes, Windows 10 is what I use to build the Paint.NET version.

> I get the error message, that CImg.h is missing. Do you have any help for me?

You need to download the matching version of [CImg](https://framagit.org/dtschump/CImg) and place it into the gmic\src directory.
The G'MIC-Qt build process checks that the G'MIC and CImg versions match, it will return an error if they do not.

The `make -C gmic/src CImg.h gmic_stdlib.h` step in the G'MIC-Qt build process downloads the appropriate versions of those files.

> First I installed QT-Creator and tried to compile the Gimp plugin.

The build process I use for the Paint.NET version is based on the CMake instructions mentioned in the Readme.
CMake works better on Windows.

Here are the CMake Windows build instructions:

1. Download and install the 64-bit version of [MSYS 2](https://www.msys2.org/).
2. Install the G'MIC-Qt dependencies using the following command in the MSYS shell:
`pacman -S git mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-curl mingw-w64-x86_64-fftw mingw-w64-x86_64-qt5`
3. Once all those files are installed you should be ready to build G'MIC-Qt
4. Make a new directory and change into it.
`mkdir gmic-build && cd gmic-build`
5. Setup G'MIC-Qt and build the standalone version:

git clone https://github.com/dtschump/gmic.git
git clone https://github.com/c-koi/gmic-qt.git
make -C gmic/src CImg.h gmic_stdlib.h
cd gmic-qt
mkdir build && cd build
cmake .. -G\"MinGW Makefiles\" -DGMIC_QT_HOST=none
mingw32-make

**Comment by c-koi** [comment] 2021-07-19 07:04
Closing this...
See [this new HOWTO](https://github.com/c-koi/gmic-qt/blob/master/STANDALONE.md) about the very first message.

**Closed** 2021-07-19 07:04 UTC
